/**
 * sipgate API
 * This is the sipgate REST API documentation. We build our new applications on this API and we invite you to use it too.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface AccountResponse {
    company?: string;

    mainProductType?: AccountResponse.MainProductTypeEnum;

    logoUrl?: string;

}
export namespace AccountResponse {
    export enum MainProductTypeEnum {
        AFFILIATE = <any> 'AFFILIATE',
        FORMERAFFILIATE = <any> 'FORMER_AFFILIATE',
        BASIC = <any> 'BASIC',
        FORMERBASIC = <any> 'FORMER_BASIC',
        SIMCONNECT = <any> 'SIMCONNECT',
        FORMERSIMCONNECT = <any> 'FORMER_SIMCONNECT',
        SIMQUADRAT = <any> 'SIMQUADRAT',
        FORMERSIMQUADRAT = <any> 'FORMER_SIMQUADRAT',
        TEAM = <any> 'TEAM',
        FORMERTEAM = <any> 'FORMER_TEAM',
        TRUNKING = <any> 'TRUNKING',
        FORMERTRUNKING = <any> 'FORMER_TRUNKING'
    }
}
