/**
 * sipgate API
 * This is the sipgate REST API documentation. We build our new applications on this API and we invite you to use it too.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface ApiUrlsResponse {
    accountUrl?: string;

    addressUrl?: string;

    addressesUrl?: string;

    addressNumbersUrl?: string;

    authorizationOauthClientsSecretUrl?: string;

    authorizationOauthClientsUrl?: string;

    authorizationOauthTokenUrl?: string;

    authorizationTokenUrl?: string;

    balanceUrl?: string;

    contactsUrl?: string;

    internalContactsUrl?: string;

    deviceCallerIdUrl?: string;

    deviceUrl?: string;

    devicesTariffAnnouncementUrl?: string;

    devicesSingleRowDisplayUrl?: string;

    deviceSimOrdersUrl?: string;

    devicesUrl?: string;

    faxlinesUrl?: string;

    faxlineNumbersUrl?: string;

    groupsUrl?: string;

    groupUserUrl?: string;

    groupNumbersUrl?: string;

    historyEntryUrl?: string;

    historyUrl?: string;

    notificationsUrl?: string;

    numberUrl?: string;

    numbersUrl?: string;

    phonelineBlockAnonymousUrl?: string;

    phonelineBusyOnBusyUrl?: string;

    phonelineDevicesUrl?: string;

    phonelineForwardingsUrl?: string;

    phonelineNumbersUrl?: string;

    phonelinesParallelForwardingUrl?: string;

    phonelinesParallelForwardingsUrl?: string;

    phonelineSipgateIoUrl?: string;

    phonelineSipgateIoLogUrl?: string;

    phonelineVoicemailGreetingUrl?: string;

    phonelineVoicemailGreetingsUrl?: string;

    phonelineVoicemailUrl?: string;

    phonelineVoicemailsUrl?: string;

    phonelinesUrl?: string;

    portingUrl?: string;

    portingsUrl?: string;

    restrictionsUrl?: string;

    sessionsCallUrl?: string;

    settingsSipgateioUrl?: string;

    smsUrl?: string;

    smsCallerIdsUrl?: string;

    translationsUrl?: string;

    userInfoUrl?: string;

    userUrl?: string;

    usersUrl?: string;

}
