/**
 * sipgate API
 * This is the sipgate REST API documentation. We build our new applications on this API and we invite you to use it too.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface HistoryEntryResponse {
    id?: string;

    source?: models.Number;

    target?: models.Number;

    sourceAlias?: string;

    targetAlias?: string;

    type?: HistoryEntryResponse.TypeEnum;

    created?: string;

    lastModified?: string;

    direction?: HistoryEntryResponse.DirectionEnum;

}
export namespace HistoryEntryResponse {
    export enum TypeEnum {
        CALL = <any> 'CALL',
        VOICEMAIL = <any> 'VOICEMAIL',
        SMS = <any> 'SMS',
        FAX = <any> 'FAX'
    }
    export enum DirectionEnum {
        MISSEDINCOMING = <any> 'MISSED_INCOMING',
        INCOMING = <any> 'INCOMING',
        OUTGOING = <any> 'OUTGOING',
        MISSEDOUTGOING = <any> 'MISSED_OUTGOING'
    }
}
