/**
 * sipgate API
 * This is the sipgate REST API documentation. We build our new applications on this API and we invite you to use it too.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface LinksResponse {
    accountsUrl?: string;

    accountTopUpUrl?: string;

    adminGroupsUrl?: string;

    adminIvrSettings?: string;

    adminProductSettingsUrl?: string;

    adminPublicPhonesUrl?: string;

    adminUsersUrl?: string;

    affiliateUrl?: string;

    appsUrl?: string;

    basicUrl?: string;

    bookConnectionUrl?: string;

    bookFaxlineUrl?: string;

    bookPhonelineUrl?: string;

    bookPhonenumberUrl?: string;

    conferenceUrl?: string;

    contactsUrl?: string;

    dashboardUrl?: string;

    faxAppUrl?: string;

    faxRescueUrl?: string;

    featureStoreUrl?: string;

    feedbackFormUrl?: string;

    forwardingsUrl?: string;

    helpdeskPhoneConfigurationUrl?: string;

    helpdeskUrl?: string;

    legacyTokenAuthenticateUrl?: string;

    loginUrl?: string;

    logoutUrl?: string;

    notificationsUrl?: string;

    personalSettingsUrl?: string;

    phonestatsUrl?: string;

    rescueUrl?: string;

    simconnectUrl?: string;

    simquadratUrl?: string;

    startUpPageUrl?: string;

    supportUrl?: string;

    teamUrl?: string;

    tokenAuthenticateUrl?: string;

    trunkingUrl?: string;

    userSettingsUrl?: string;

    mnpFaqUrl?: string;

}
