/**
 * sipgate API
 * This is the sipgate REST API documentation. We build our new applications on this API and we invite you to use it too.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface RestrictionItem {
    restriction?: RestrictionItem.RestrictionEnum;

    value?: any;

}
export namespace RestrictionItem {
    export enum RestrictionEnum {
        CANCREATEREGISTERDEVICE = <any> 'CAN_CREATE_REGISTER_DEVICE',
        CANCREATEMOBILEDEVICE = <any> 'CAN_CREATE_MOBILE_DEVICE',
        CANCREATEPHONELINEEXTENSION = <any> 'CAN_CREATE_PHONELINE_EXTENSION',
        CANBOOKPHONELINEFEATURE = <any> 'CAN_BOOK_PHONELINE_FEATURE',
        MAXPARALLELFORWARDINGS = <any> 'MAX_PARALLEL_FORWARDINGS',
        MAXFORWARDINGS = <any> 'MAX_FORWARDINGS',
        NOTIFICATIONRESTRICTIONS = <any> 'NOTIFICATION_RESTRICTIONS',
        GSUITEEXTENSION = <any> 'GSUITE_EXTENSION',
        CANCREATEFAXEXTENSION = <any> 'CAN_CREATE_FAX_EXTENSION',
        CANBOOKFAXFEATURE = <any> 'CAN_BOOK_FAX_FEATURE',
        CANSENDFAX = <any> 'CAN_SEND_FAX',
        CANRECEIVEFAX = <any> 'CAN_RECEIVE_FAX'
    }
}
