export * from './AccountApi';
import { AccountApi }  from './AccountApi';
export * from './AddressesApi';
import { AddressesApi }  from './AddressesApi';
export * from './AppApi';
import { AppApi }  from './AppApi';
export * from './AuthorizationApi';
import { AuthorizationApi }  from './AuthorizationApi';
export * from './BalanceApi';
import { BalanceApi }  from './BalanceApi';
export * from './ContactsApi';
import { ContactsApi }  from './ContactsApi';
export * from './DevicesApi';
import { DevicesApi }  from './DevicesApi';
export * from './FaxlinesApi';
import { FaxlinesApi }  from './FaxlinesApi';
export * from './GroupsApi';
import { GroupsApi }  from './GroupsApi';
export * from './HistoryApi';
import { HistoryApi }  from './HistoryApi';
export * from './InternalContactsApi';
import { InternalContactsApi }  from './InternalContactsApi';
export * from './NotificationsApi';
import { NotificationsApi }  from './NotificationsApi';
export * from './NumbersApi';
import { NumbersApi }  from './NumbersApi';
export * from './PasswordResetApi';
import { PasswordResetApi }  from './PasswordResetApi';
export * from './PhonelinesApi';
import { PhonelinesApi }  from './PhonelinesApi';
export * from './PortingsApi';
import { PortingsApi }  from './PortingsApi';
export * from './RestrictionsApi';
import { RestrictionsApi }  from './RestrictionsApi';
export * from './SessionsApi';
import { SessionsApi }  from './SessionsApi';
export * from './SettingsApi';
import { SettingsApi }  from './SettingsApi';
export * from './SmsApi';
import { SmsApi }  from './SmsApi';
export * from './TranslationsApi';
import { TranslationsApi }  from './TranslationsApi';
export * from './UrlsApi';
import { UrlsApi }  from './UrlsApi';
export * from './UsersApi';
import { UsersApi }  from './UsersApi';
export const APIS = [ AccountApi, AddressesApi, AppApi, AuthorizationApi, BalanceApi, ContactsApi, DevicesApi, FaxlinesApi, GroupsApi, HistoryApi, InternalContactsApi, NotificationsApi, NumbersApi, PasswordResetApi, PhonelinesApi, PortingsApi, RestrictionsApi, SessionsApi, SettingsApi, SmsApi, TranslationsApi, UrlsApi, UsersApi, ];
