/**
 * sipgate API
 * This is the sipgate REST API documentation. We build our new applications on this API and we invite you to use it too.
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { Http, Headers, URLSearchParams }                    from '@angular/http';
import { RequestMethod, RequestOptions, RequestOptionsArgs } from '@angular/http';
import { Response, ResponseContentType }                     from '@angular/http';

import { Observable }                                        from 'rxjs/Observable';
import 'rxjs/add/operator/map';

import * as models                                           from '../model/models';
import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';

/* tslint:disable:no-unused-variable member-ordering */


@Injectable()
export class HistoryApi {
    protected basePath = 'https://localhost/v1';
    public defaultHeaders: Headers = new Headers();
    public configuration: Configuration = new Configuration();

    constructor(protected http: Http, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
        }
    }

    /**
     * Deletes a history entry
     *
     * @param userId e.g. w0
     * @param entryId e.g. 1337
     */
    public deleteHistoryEntry(userId: string, entryId: string, extraHttpRequestParams?: any): Observable<{}> {
        return this.deleteHistoryEntryWithHttpInfo(userId, entryId, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * Returns the history of calls and voicemails
     *
     * @param userId e.g. w0
     * @param phonelineId e.g. p0
     * @param types e.g. VOICEMAIL
     * @param directions e.g. MISSED_INCOMING
     * @param offset e.g. 42
     * @param limit e.g. 23
     */
    public getHistory(userId: string, phonelineId?: string, types?: Array<string>, directions?: Array<string>, offset?: number, limit?: number, extraHttpRequestParams?: any): Observable<models.HistoryResponse> {
        return this.getHistoryWithHttpInfo(userId, phonelineId, types, directions, offset, limit, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }


    /**
     * Deletes a history entry
     *
     * @param userId e.g. w0
     * @param entryId e.g. 1337
     */
    public deleteHistoryEntryWithHttpInfo(userId: string, entryId: string, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + `/${userId}/history/${entryId}`;

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // verify required parameter 'userId' is not null or undefined
        if (userId === null || userId === undefined) {
            throw new Error('Required parameter userId was null or undefined when calling deleteHistoryEntry.');
        }
        // verify required parameter 'entryId' is not null or undefined
        if (entryId === null || entryId === undefined) {
            throw new Error('Required parameter entryId was null or undefined when calling deleteHistoryEntry.');
        }
        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        // to determine the Accept header
        let produces: string[] = [
            'application/json'
        ];

        // authentication (oauth2) required
        // oauth required
        if (this.configuration.accessToken) {
            let accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers.set('Authorization', 'Bearer ' + accessToken);
        }

        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Delete,
            headers: headers,
            search: queryParameters
        });

        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = (<any>Object).assign(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

    /**
     * Returns the history of calls and voicemails
     *
     * @param userId e.g. w0
     * @param phonelineId e.g. p0
     * @param types e.g. VOICEMAIL
     * @param directions e.g. MISSED_INCOMING
     * @param offset e.g. 42
     * @param limit e.g. 23
     */
    public getHistoryWithHttpInfo(userId: string, phonelineId?: string, types?: Array<string>, directions?: Array<string>, offset?: number, limit?: number, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + `/${userId}/history`;

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // verify required parameter 'userId' is not null or undefined
        if (userId === null || userId === undefined) {
            throw new Error('Required parameter userId was null or undefined when calling getHistory.');
        }
        if (phonelineId !== undefined) {
            queryParameters.set('phonelineId', <any>phonelineId);
        }

        if (types) {
            types.forEach((element) => {
                queryParameters.append('types', <any>element);
            })
        }

        if (directions) {
            directions.forEach((element) => {
                queryParameters.append('directions', <any>element);
            })
        }

        if (offset !== undefined) {
            queryParameters.set('offset', <any>offset);
        }

        if (limit !== undefined) {
            queryParameters.set('limit', <any>limit);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        // to determine the Accept header
        let produces: string[] = [
            'application/json'
        ];

        // authentication (oauth2) required
        // oauth required
        if (this.configuration.accessToken) {
            let accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers.set('Authorization', 'Bearer ' + accessToken);
        }

        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Get,
            headers: headers,
            search: queryParameters
        });

        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = (<any>Object).assign(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

}
